### PR TITLE
Update mcc codes from VISA Merchant Data Standards.

### PR DESCRIPTION
**Pull request by jsmpereira**
http://usa.visa.com/download/merchants/Visa-Merchant-Data-Standards-Manual-Nov-2014.pdf

Summary of changes, p. i.

### CODE REVIEW

**Comment by greggles** [comment]
Awesome help. I appreciate that you updated all of the files - thanks!

**Comment by jsmpereira** [comment]
@greggles Glad to help. Not sure though about the completeness of the contribution. I've looked around and couldn't find USDA or IRS references to the new codes.

**Comment by greggles** [comment]
I just meant completeness in terms of you modifying all of the file types. If IRS or USDA output new files then we can see about updating them, but the point to me is really that by aggregating multiple data sources we can come up with one decent list.

**Comment by jsmpereira** [comment]
Yeah, I got that :stuck_out_tongue:

**Comment by jdleonard** [comment]
Hi all. Just a note that there's a newer source doc. I haven't examined it to determine if there are any relevant changes. http://usa.visa.com/download/merchants/Visa-USA-Interchange-Reimbursement-Fees-2015-April-18.pdf

**Pull request merged**
